package com.module.parser.wsdlGen;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.14
 * 2020-08-20T12:31:49.201+08:00
 * Generated source version: 3.2.14
 *
 */
@WebServiceClient(name = "LoginResult",
                  wsdlLocation = "file:/C:/Users/lizhuangjie.chnet/IdeaProjects/parser/orderDispatch/src/main/resources/wsdl/LoginResult.wsdl",
                  targetNamespace = "http://module.com/parser/entity/result/LoginResult")
public class LoginResult extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://module.com/parser/entity/result/LoginResult", "LoginResult");
    public final static QName LoginResultPort = new QName("http://module.com/parser/entity/result/LoginResult", "LoginResultPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/lizhuangjie.chnet/IdeaProjects/parser/orderDispatch/src/main/resources/wsdl/LoginResult.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(LoginResult.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/lizhuangjie.chnet/IdeaProjects/parser/orderDispatch/src/main/resources/wsdl/LoginResult.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public LoginResult(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LoginResult(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LoginResult() {
        super(WSDL_LOCATION, SERVICE);
    }

    public LoginResult(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public LoginResult(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public LoginResult(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns LoginResultPortType
     */
    @WebEndpoint(name = "LoginResultPort")
    public LoginResultPortType getLoginResultPort() {
        return super.getPort(LoginResultPort, LoginResultPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoginResultPortType
     */
    @WebEndpoint(name = "LoginResultPort")
    public LoginResultPortType getLoginResultPort(WebServiceFeature... features) {
        return super.getPort(LoginResultPort, LoginResultPortType.class, features);
    }

}
