
package com.module.parser.wsdlGen;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.14
 * 2020-08-20T12:31:49.055+08:00
 * Generated source version: 3.2.14
 *
 */
public final class LoginResultPortType_LoginResultPort_Client {

    private static final QName SERVICE_NAME = new QName("http://module.com/parser/entity/result/LoginResult", "LoginResult");

    private LoginResultPortType_LoginResultPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = LoginResult.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        LoginResult ss = new LoginResult(wsdlURL, SERVICE_NAME);
        LoginResultPortType port = ss.getLoginResultPort();

        {
        System.out.println("Invoking setTicketId...");
        java.lang.String _setTicketId_ticketId = "";
        port.setTicketId(_setTicketId_ticketId);


        }
        {
        System.out.println("Invoking canEqual...");
        com.module.parser.wsdlGen.Object _canEqual_other = null;
        boolean _canEqual__return = port.canEqual(_canEqual_other);
        System.out.println("canEqual.result=" + _canEqual__return);


        }
        {
        System.out.println("Invoking getWorkType...");
        java.lang.String _getWorkType__return = port.getWorkType();
        System.out.println("getWorkType.result=" + _getWorkType__return);


        }
        {
        System.out.println("Invoking setWorkType...");
        java.lang.String _setWorkType_workType = "";
        port.setWorkType(_setWorkType_workType);


        }
        {
        System.out.println("Invoking getDeviceMType...");
        java.lang.String _getDeviceMType__return = port.getDeviceMType();
        System.out.println("getDeviceMType.result=" + _getDeviceMType__return);


        }
        {
        System.out.println("Invoking isHalt...");
        boolean _isHalt__return = port.isHalt();
        System.out.println("isHalt.result=" + _isHalt__return);


        }
        {
        System.out.println("Invoking getMoveCapacity...");
        java.lang.String _getMoveCapacity__return = port.getMoveCapacity();
        System.out.println("getMoveCapacity.result=" + _getMoveCapacity__return);


        }
        {
        System.out.println("Invoking getTicketId...");
        java.lang.String _getTicketId__return = port.getTicketId();
        System.out.println("getTicketId.result=" + _getTicketId__return);


        }
        {
        System.out.println("Invoking setHalt...");
        boolean _setHalt_isHalt = false;
        port.setHalt(_setHalt_isHalt);


        }
        {
        System.out.println("Invoking setDeviceNo...");
        java.lang.String _setDeviceNo_deviceNo = "";
        port.setDeviceNo(_setDeviceNo_deviceNo);


        }
        {
        System.out.println("Invoking setDeviceMType...");
        java.lang.String _setDeviceMType_deviceMType = "";
        port.setDeviceMType(_setDeviceMType_deviceMType);


        }
        {
        System.out.println("Invoking hashCode...");
        int _hashCode__return = port.hashCode();
        System.out.println("hashCode.result=" + _hashCode__return);


        }
        {
        System.out.println("Invoking equals...");
        com.module.parser.wsdlGen.Object _equals_o = null;
        boolean _equals__return = port.equals(_equals_o);
        System.out.println("equals.result=" + _equals__return);


        }
        {
        System.out.println("Invoking setMoveCapacity...");
        java.lang.String _setMoveCapacity_moveCapacity = "";
        port.setMoveCapacity(_setMoveCapacity_moveCapacity);


        }
        {
        System.out.println("Invoking getDeviceNo...");
        java.lang.String _getDeviceNo__return = port.getDeviceNo();
        System.out.println("getDeviceNo.result=" + _getDeviceNo__return);


        }
        {
        System.out.println("Invoking toString...");
        java.lang.String _toString__return = port.toString();
        System.out.println("toString.result=" + _toString__return);


        }

        System.exit(0);
    }

}
