package com.module.parser.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.14
 * 2020-08-20T23:59:59.261+08:00
 * Generated source version: 3.2.14
 *
 */
@WebService(targetNamespace = "http://module.com/parser/entity/test/CTOS", name = "CTOSPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface CTOSPortType {

    @WebMethod(action = "urn:doLoginResult")
    @RequestWrapper(localName = "doLoginResult", targetNamespace = "http://module.com/parser/entity/test/CTOS", className = "com.module.parser.cxf.DoLoginResult")
    @ResponseWrapper(localName = "doLoginResultResponse", targetNamespace = "http://module.com/parser/entity/test/CTOS", className = "com.module.parser.cxf.DoLoginResultResponse")
    @WebResult(name = "return", targetNamespace = "http://module.com/parser/entity/test/CTOS")
    public java.lang.String doLoginResult(
        @WebParam(name = "loginResult", targetNamespace = "http://module.com/parser/entity/test/CTOS")
        com.module.parser.cxf.LoginResult loginResult
    );

    @WebMethod(action = "urn:doLogin")
    @RequestWrapper(localName = "doLogin", targetNamespace = "http://module.com/parser/entity/test/CTOS", className = "com.module.parser.cxf.DoLogin")
    @ResponseWrapper(localName = "doLoginResponse", targetNamespace = "http://module.com/parser/entity/test/CTOS", className = "com.module.parser.cxf.DoLoginResponse")
    @WebResult(name = "return", targetNamespace = "http://module.com/parser/entity/test/CTOS")
    public java.lang.String doLogin(
        @WebParam(name = "login", targetNamespace = "http://module.com/parser/entity/test/CTOS")
        com.module.parser.cxf.Login login
    );
}
