
package com.module.parser.cxf;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.14
 * 2020-08-20T23:59:59.238+08:00
 * Generated source version: 3.2.14
 *
 */
public final class CTOSPortType_CTOSPort_Client {

    private static final QName SERVICE_NAME = new QName("http://module.com/parser/entity/test/CTOS", "CTOS");

    private CTOSPortType_CTOSPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CTOS.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        CTOS ss = new CTOS(wsdlURL, SERVICE_NAME);
        CTOSPortType port = ss.getCTOSPort();

        {
        System.out.println("Invoking doLoginResult...");
        com.module.parser.cxf.LoginResult _doLoginResult_loginResult = new com.module.parser.cxf.LoginResult();
        java.lang.String _doLoginResult__return = port.doLoginResult(_doLoginResult_loginResult);
        System.out.println("doLoginResult.result=" + _doLoginResult__return);


        }
        {
        System.out.println("Invoking doLogin...");
        com.module.parser.cxf.Login _doLogin_login = new com.module.parser.cxf.Login();
        java.lang.String _doLogin__return = port.doLogin(_doLogin_login);
        System.out.println("doLogin.result=" + _doLogin__return);


        }

        System.exit(0);
    }

}
