
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.module.parser.cxf;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.14
 * 2020-08-20T23:59:59.253+08:00
 * Generated source version: 3.2.14
 *
 */

@javax.jws.WebService(
                      serviceName = "CTOS",
                      portName = "CTOSPort",
                      targetNamespace = "http://module.com/parser/entity/test/CTOS",
                      wsdlLocation = "file:/C:/Users/Administrator/IdeaProjects/parser/orderDispatch/src/main/resources/toWsdl/CTOS.wsdl",
                      endpointInterface = "com.module.parser.cxf.CTOSPortType")

public class CTOSPortImpl implements CTOSPortType {

    private static final Logger LOG = Logger.getLogger(CTOSPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.module.parser.cxf.CTOSPortType#doLoginResult(com.module.parser.cxf.LoginResult loginResult)*
     */
    public java.lang.String doLoginResult(com.module.parser.cxf.LoginResult loginResult) {
        LOG.info("Executing operation doLoginResult");
        System.out.println(loginResult);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.module.parser.cxf.CTOSPortType#doLogin(com.module.parser.cxf.Login login)*
     */
    public java.lang.String doLogin(com.module.parser.cxf.Login login) {
        LOG.info("Executing operation doLogin");
        System.out.println(login);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
