
package com.module.parser.cxf;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.2.14
 * 2020-08-20T23:59:59.267+08:00
 * Generated source version: 3.2.14
 *
 */

public class CTOSPortType_CTOSPort_Server{

    protected CTOSPortType_CTOSPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new CTOSPortImpl();
        String address = "http://localhost:8080/axis2/services/CTOS";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new CTOSPortType_CTOSPort_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
