package com.module.parser.cxf2;

import javax.jws.WebService;

/**
 * This class was generated by Apache CXF 3.2.14
 * 2020-08-21T10:57:20.723+08:00
 * Generated source version: 3.2.14
 *
 */
@WebService(targetNamespace = "http://module.com/parser/entity/test/LoginResultTest", name = "LoginResultTestPortType")
public interface LoginResultTestPortType {
}
