
package com.module.parser.cxf2;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebService;

/**
 * This class was generated by Apache CXF 3.2.14
 * 2020-08-21T10:57:20.705+08:00
 * Generated source version: 3.2.14
 *
 */
public final class LoginResultTestPortType_LoginResultTestPort_Client {

    private static final QName SERVICE_NAME = new QName("http://module.com/parser/entity/test/LoginResultTest", "LoginResultTest");

    private LoginResultTestPortType_LoginResultTestPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = LoginResultTest.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        LoginResultTest ss = new LoginResultTest(wsdlURL, SERVICE_NAME);
        LoginResultTestPortType port = ss.getLoginResultTestPort();


        System.exit(0);
    }

}
