
package com.module.parser.cxf2;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.2.14
 * 2020-08-21T10:57:20.727+08:00
 * Generated source version: 3.2.14
 *
 */

public class LoginResultTestPortType_LoginResultTestPort_Server{

    protected LoginResultTestPortType_LoginResultTestPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new LoginResultTestPortImpl();
        String address = "http://localhost:8080/axis2/services/LoginResultTest";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new LoginResultTestPortType_LoginResultTestPort_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
