
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.module.parser.cxf2;

import java.util.logging.Logger;
import javax.jws.WebService;

/**
 * This class was generated by Apache CXF 3.2.14
 * 2020-08-21T10:57:20.717+08:00
 * Generated source version: 3.2.14
 *
 */

@javax.jws.WebService(
                      serviceName = "LoginResultTest",
                      portName = "LoginResultTestPort",
                      targetNamespace = "http://module.com/parser/entity/test/LoginResultTest",
                      wsdlLocation = "file:/C:/Users/lizhuangjie.chnet/IdeaProjects/parser/orderDispatch/src/main/resources/toWsdl2/LoginResultTest.wsdl",
                      endpointInterface = "com.module.parser.cxf2.LoginResultTestPortType")

public class LoginResultTestPortImpl implements LoginResultTestPortType {

    private static final Logger LOG = Logger.getLogger(LoginResultTestPortImpl.class.getName());

}
